name = "earnings-worker"
main = "src/main.ts"
routes = ["pf.bforecast.com/*"]
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "earnings-db"
database_id = "ead78c5a-59ee-46e8-9ae7-d8e02dfbc4bf"

[triggers]
# Split cron schedule to capture Mon-Fri EST hours resiliently in UTC:
# - Mon-Fri 4:00-7:59 PM EST -> UTC Mon-Fri 20:00-23:59 (Day MON-FRI)
# - Mon-Fri 8:00-11:59 PM EST -> UTC Tue-Sat 00:00-03:59 (Day TUE-SAT)
crons = ["*/1 20-23 * * MON-FRI", "*/1 0-3 * * TUE-SAT"]

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1 # 100% sampling

[ai]
binding = "AI"
